POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9saXZpYWhvcmoiLCJpZCI6IjYzYzI3YmNhOGVjYTNhMzI3ZGJiYmFmYyIsImlhdCI6MTY3MzY5MTk2Mn0.3_2DzbZt8OzqWmcQlRudJnKqncn3JbP8D3njG09x6BY

{
  "title": "testititle3",
  "author": "testiauthor3",
  "url": "testiurl3",
  "likes": 1,
  "userId": "63c27bca8eca3a327dbbbafc"

}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "oliviahorj",
  "name": "Olivia",
  "password": "topsecret"
}

###
post http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "oliviahorj",
  "password": "topsecret"
}


###
delete http://localhost:3001/api/blogs/63c2834b2c724452bea0e0fd
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9saXZpYWhvcmoiLCJpZCI6IjYzYzI3YmNhOGVjYTNhMzI3ZGJiYmFmYyIsImlhdCI6MTY3MzY5MTk2Mn0.3_2DzbZt8OzqWmcQlRudJnKqncn3JbP8D3njG09x6BY

###
get http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9saXZpYWhvcmoiLCJpZCI6IjYzYzI3YmNhOGVjYTNhMzI3ZGJiYmFmYyIsImlhdCI6MTY3MzY5MTk2Mn0.3_2DzbZt8OzqWmcQlRudJnKqncn3JbP8D3njG09x6BY
