
put http://localhost:3000/todos/647e032fc6d27b07709d4d47
Content-Type: application/json

{
  "text": "Write better code",
  "done": true
}

###
get http://localhost:3000/todos/647e032fc6d27b07709d4d47

###
post http://localhost:3000/todos
Content-Type: :application/json

{
  "text": "Testi2",
  "done": true
}